services:

  hazelcast-management-center:
    image: hazelcast/management-center:latest
    environment:
      - LOGGING_LEVEL=INFO
      - MAX_HEAP_SIZE='512M'
      - JAVA_OPTS=
        -Xms512m 
        -Dhazelcast.mc.http.port=9080 
        -Dhazelcast.mc.https.port=9443
      - MC_INIT_CMD=~/bin/mc-conf.sh cluster add -ma hazelcast-member:5701 -cn dev -v
    ports:
      - "9080:9080"

  hazelcast-member:
    image: hazelcast/hazelcast:latest
    ports:
      - "5701"

  postgres:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD:-passwordForHhVolgograd}
      POSTGRES_USER: ${POSTGRES_USER_NAME:-hhVolgograd}
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes:
      - "./postgres:/var/lib/postgresql/data/pgdata"

version: "3.9"