services:

  hazelcast-management-center:
    environment:
      JAVA_OPTS:
        -Dhazelcast.mc.http.port=9080
        -Dhazelcast.mc.https.port=9443
        -Xms512m
      LOGGING_LEVEL: INFO
      MAX_HEAP_SIZE: '512M'
      MC_INIT_CMD: ~/bin/mc-conf.sh cluster add -ma hazelcast-member:5701 -cn dev -v
    image: hazelcast/management-center:latest
    ports:
      - "9080:9080"

  hazelcast-member:
    environment:
      HZ_NETWORK_PUBLICADDRESS: localhost:5701
    image: hazelcast/hazelcast:latest
    ports:
      - "5701:5701"

  postgres:
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD:-passwordForHhVolgograd}
      POSTGRES_USER: ${POSTGRES_USER_NAME:-hhVolgograd}
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes:
      - "./postgres:/var/lib/postgresql/data/pgdata"

version: "3.9"