jwt:
  secret: ${JWT_SECRET:hhVolgogradSecretMustHave32chars+}

logging:
  file:
    path: ${LOG_HOME:/home/zapisator/hh-volgograd/log}
  level:
    org:
      hibernate:
        SQL: error
    root: info

project:
  mail:
    from: ${MAIL_FROM}

server:
  port: 8080

spring:
  datasource:
    liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml
      enabled: false
    password: ${POSTGRES_PASSWORD:passwordForHhVolgograd}
    pool:
      initial-size: 5
      max-idle-time: 10s
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${POSTGRES_USER_NAME:hhVolgograd}
  jpa:
    open-in-view: false
  mail:
    debug: true
    host: ${MAIL_HOST:smtp.rambler.ru}
    password: ${MAIL_PASSWORD}
    port: "${MAIL_PORT:465}"
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
    transport:
      protocol: smtp
    username: ${MAIL_USERNAME}
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: dev

